apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.deployment.deploymentsecret }}
  namespace: {{ .Values.namespace }}
data:
  .dockerconfigjson: {{ .Values.secret.dockersecret }}
type: kubernetes.io/dockerconfigjson