apiVersion: v1
kind: Secret
metadata:
  name: {{ include "selfhostedagents.name" . }}
  {{- include "selfhostedagents.namespace" . | nindent 2 }} 
data:
  .dockerconfigjson: ewogICAgICAgICJhdXRocyI6IHsKICAgICAgICAgICAgICAgICJ2YW50YWdlYWNyZWFzdHVzMi5henVyZWNyLmlvIjogewogICAgICAgICAgICAgICAgICAgICAgICAiYXV0aCI6ICJkbUZ1ZEdGblpXRmpjbVZoYzNSMWN6STZMME1yWkM5SlQxTk5WbGhpT1U1QlpHaHpUbWRRZW5ocGJFaERNbVJvVTJNPSIKICAgICAgICAgICAgICAgIH0KICAgICAgICB9Cn0=
type: kubernetes.io/dockerconfigjson
