{{- if .Values.secret.enabled -}}
apiVersion: v1
kind: Secret
type: {{ .Values.secret.type | default "Opaque" }}
metadata:
  name: secret-{{ include "apps.name" . }}
  {{- include "apps.namespace" . | nindent 2 }}

{{- with .Values.secret.stringData }}  
stringData:
  {{- toYaml . | nindent 2 }}
{{- end }}

{{ if .Values.secret.data }}
data:
{{- range $key,$value := .Values.secret.data }}  
  {{- $key | nindent 2 }}: {{ $value | b64enc }}
{{- end }}
{{ end }}  

{{- end -}}