{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-{{ include "apps.name" . }}
  {{- include "apps.namespace" . | nindent 2 }}
  labels:
    {{- include "apps.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
